# Ruff configuration file
line-length = 100
target-version = "py311"

[lint]
select = ["E", "F", "I", "B", "C4", "UP"]
ignore = ["E501", "B008", "C901"]

[lint.per-file-ignores]
"__init__.py" = ["F401"]

[format]
quote-style = "double"
indent-style = "space"

